#!/usr/bin/env node
// Extracts SYSTEM_PROMPT + PROMPT_VERSION from the Rust prompt module and the
// MISSION.md text into generated modules, so the site can never drift from
// what the judge actually sends or what the repo's mission says.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const promptRs = readFileSync(resolve(here, "../../crates/omapak-judge/src/prompt.rs"), "utf8");

const version = promptRs.match(/pub const PROMPT_VERSION: &str = "([^"]+)"/)?.[1];
const raw = promptRs.match(/pub const SYSTEM_PROMPT: &str = r#"(.*?)"#;/s)?.[1];
if (!version || !raw) {
  console.error("could not extract PROMPT_VERSION/SYSTEM_PROMPT from prompt.rs");
  process.exit(1);
}

const mission = readFileSync(resolve(here, "../../MISSION.md"), "utf8");

const out = `// GENERATED by scripts/sync-rubric.mjs — do not edit; sources of truth are
// crates/omapak-judge/src/prompt.rs and MISSION.md.
export const PROMPT_VERSION = "${version}";
export const JUDGE_PROMPT = ${JSON.stringify(raw)};
export const MISSION_MD = ${JSON.stringify(mission)};
`;

mkdirSync(resolve(here, "../src/lib/generated"), { recursive: true });
writeFileSync(resolve(here, "../src/lib/generated/rubric.ts"), out);
console.log(
  `rubric v${version} synced (${raw.length} chars) · mission synced (${mission.length} chars)`,
);
